# -*- coding: utf-8 -*-
"""exp 21

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCCcNSC8j2N_xYHdGO58TTGZ6aVcNk6Q
"""

import cv2
import numpy as np

# Updated path to an image available in the Colab environment
img = cv2.imread('/content/map 2 (1).jpg') # Load as color image by default

# Check if the image was loaded successfully
if img is None:
    print("Error: Could not load the image. Please check the path.")
else:
    kernel = np.array([[1,1,1], [1,-8,1], [1,1,1]])
    sharpened = cv2.filter2D(img, -1, kernel)
    cv2.imwrite('Sharpened_Image.jpg', sharpened)
    print("Sharpened image saved as 'Sharpened_Image.jpg'")

import matplotlib.pyplot as plt

# Load the images
original_img = cv2.imread('/content/map 2 (1).jpg')
sharpened_img_original_kernel = cv2.imread('Sharpened_Image.jpg')
sharpened_img_stronger_kernel = cv2.imread('Sharpened_Image_Stronger.jpg')

# Convert images from BGR to RGB for correct display in matplotlib
original_img_rgb = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
sharpened_img_original_kernel_rgb = cv2.cvtColor(sharpened_img_original_kernel, cv2.COLOR_BGR2RGB)
sharpened_img_stronger_kernel_rgb = cv2.cvtColor(sharpened_img_stronger_kernel, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(20, 8))

plt.subplot(1, 3, 1)
plt.imshow(original_img_rgb)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(sharpened_img_original_kernel_rgb)
plt.title('Sharpened (Original Kernel)')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(sharpened_img_stronger_kernel_rgb)
plt.title('Sharpened (Stronger Kernel)')
plt.axis('off')

plt.tight_layout()
plt.show()