# -*- coding: utf-8 -*-
"""EXP 23

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_ZlOqkCY6kJxEEY97xGY_m0zQrSrrDI
"""

from PIL import Image, ImageFilter
import matplotlib.pyplot as plt
from google.colab import files

# Upload the image file
uploaded = files.upload()

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

# Open the image using PIL
im1 = Image.open(image_filename)

# Apply UnsharpMask filter
im2 = im1.filter(ImageFilter.UnsharpMask(radius=3, percent=200, threshold=5))

# Display images using matplotlib
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(im1)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(im2)
plt.title('Sharpened Image (UnsharpMask)')
plt.axis('off')

plt.tight_layout()
plt.show()