# -*- coding: utf-8 -*-
"""EXP 25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_ZlOqkCY6kJxEEY97xGY_m0zQrSrrDI
"""

import cv2
import numpy as np
from google.colab import files

# Upload the image file
uploaded = files.upload()

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

image = cv2.imread(image_filename)

# Check if the image was loaded successfully
if image is not None:
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    gradient_x = cv2.Sobel(gray, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=3)
    gradient_y = cv2.Sobel(gray, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=3)
    gradient = cv2.subtract(gradient_x, gradient_y)

    # Ensure the gradient image is in a displayable format for saving if it's float
    # Convert to uint8 and clip values to 0-255 range
    gradient_uint8 = np.clip(gradient, 0, 255).astype(np.uint8)
    cv2.imwrite('sharpened_image3.jpg', gradient_uint8)
    print(f"Sharpened image saved as sharpened_image3.jpg")
else:
    print(f"Error: Could not load image from {image_filename}")

import matplotlib.pyplot as plt

# Load the original image (from the uploaded filename)
original_image_display = cv2.imread(image_filename)
original_image_display = cv2.cvtColor(original_image_display, cv2.COLOR_BGR2RGB)

# Load the sharpened image saved previously
sharpened_image_loaded = cv2.imread('sharpened_image3.jpg')
sharpened_image_loaded = cv2.cvtColor(sharpened_image_loaded, cv2.COLOR_BGR2RGB)

# Display images side-by-side
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
plt.imshow(original_image_display)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
plt.imshow(sharpened_image_loaded)
plt.title('Sharpened Image (Sobel)')
plt.axis('off')

plt.tight_layout()
plt.show()