# -*- coding: utf-8 -*-
"""e 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdqkI6OZCX4xRKYBjVnVZdvpLloldwUe
"""

from google.colab import files
files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Open video file (or use 0 for webcam)
cap = cv2.VideoCapture('video.mp4')

if not cap.isOpened():
    print("Error: Could not open video file or webcam.")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        rows, cols = frame.shape[:2]

        # Define 4 points in original frame
        pts1 = np.float32([[100, 100],
                           [400, 100],
                           [100, 300],
                           [400, 300]])

        # Define destination points
        pts2 = np.float32([[50, 150],
                           [450, 100],
                           [150, 350],
                           [400, 300]])

        # Get perspective transform matrix
        M = cv2.getPerspectiveTransform(pts1, pts2)

        # Apply transformation
        warped = cv2.warpPerspective(frame, M, (cols, rows))

        # Display
        print("Original Video Frame:")
        cv2_imshow(frame)
        print("Perspective Transformed Video Frame:")
        cv2_imshow(warped)

        # In Colab, there is no interactive waitKey, so we show one frame and break.
        # To process all frames, you might need to save them or use a different visualization approach.
        # For this example, we'll just show the first frame or break if it's an actual video.
        break # To avoid endless loop in interactive display for demonstration

    cap.release()