# -*- coding: utf-8 -*-
"""exp 18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCCcNSC8j2N_xYHdGO58TTGZ6aVcNk6Q
"""

import matplotlib.pyplot as plt

# Read the Sobel X and Sobel Y images
sobel_x_image = cv2.imread('sobel_x.jpg', 0) # Read as grayscale
sobel_y_image = cv2.imread('sobel_y.jpg', 0) # Read as grayscale

# Create a figure with two subplots
plt.figure(figsize=(12, 6))

# Subplot for Sobel X
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
plt.imshow(sobel_x_image, cmap='gray')
plt.title('Sobel X Edge Detection')
plt.axis('off')

# Subplot for Sobel Y
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
plt.imshow(sobel_y_image, cmap='gray')
plt.title('Sobel Y Edge Detection')
plt.axis('off')

plt.tight_layout() # Adjust layout to prevent overlapping titles/labels
plt.show()