# -*- coding: utf-8 -*-
"""exp 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCCcNSC8j2N_xYHdGO58TTGZ6aVcNk6Q
"""

plt.figure(figsize=(15, 7))

plt.subplot(1, 2, 1)
plt.imshow(edges, cmap='gray')
plt.title('Combined Sobel Edges')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(canny_edges, cmap='gray')
plt.title('Canny Edges')
plt.axis('off')

plt.show()