# -*- coding: utf-8 -*-
"""exp 20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCCcNSC8j2N_xYHdGO58TTGZ6aVcNk6Q
"""

import matplotlib.pyplot as plt

# Load the images
original_img = cv2.imread('/content/map 2 (1).jpg')
sharpened_img_original_kernel = cv2.imread('Sharpened_Image.jpg')
sharpened_img_stronger_kernel = cv2.imread('Sharpened_Image_Stronger.jpg')

# Convert images from BGR to RGB for correct display in matplotlib
original_img_rgb = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
sharpened_img_original_kernel_rgb = cv2.cvtColor(sharpened_img_original_kernel, cv2.COLOR_BGR2RGB)
sharpened_img_stronger_kernel_rgb = cv2.cvtColor(sharpened_img_stronger_kernel, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(20, 8))

plt.subplot(1, 3, 1)
plt.imshow(original_img_rgb)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(sharpened_img_original_kernel_rgb)
plt.title('Sharpened (Original Kernel)')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(sharpened_img_stronger_kernel_rgb)
plt.title('Sharpened (Stronger Kernel)')
plt.axis('off')

plt.tight_layout()
plt.show()