# -*- coding: utf-8 -*-
"""exp 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12glIugWcg9PUoJb1Z3qZeX-UKvWVvduN
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Step 1: Read the image
image = cv2.imread('Screenshot 2026-07-25 085808.png')   # replace with your image path

# Check if image loaded properly
if image is None:
    print("Error: Image not found!")
    exit()

# Step 2: Create a kernel (structuring element)
kernel = np.ones((5,5), np.uint8)   # 5x5 matrix

# Step 3: Apply erosion
eroded_image = cv2.erode(image, kernel, iterations=1)

# Step 4: Display images
cv2_imshow(image)
cv2_imshow(eroded_image)

# Wait and close (not needed in Colab)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# Step 5: Save output (optional)
cv2.imwrite('eroded_output.jpg', eroded_image)