# -*- coding: utf-8 -*-
"""exp 16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCCcNSC8j2N_xYHdGO58TTGZ6aVcNk6Q
"""

import cv2
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt

# Step 1: Upload image
uploaded = files.upload()

# Get the uploaded file name
image_path = list(uploaded.keys())[0]

# Step 2: Read the image
image = cv2.imread(image_path)

# Step 3: Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Step 4: Apply Gaussian Blur
blur = cv2.GaussianBlur(gray, (5, 5), 0)

# Step 5: Apply Canny Edge Detection
edges = cv2.Canny(blur, 100, 200)

# Step 6: Display results
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1,2,2)
plt.title("Canny Edge Detection")
plt.imshow(edges, cmap='gray')
plt.axis('off')

plt.show()