# -*- coding: utf-8 -*-
"""EXP 22

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_ZlOqkCY6kJxEEY97xGY_m0zQrSrrDI
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from google.colab.patches import cv2_imshow # Import cv2_imshow

# Upload the image file
uploaded = files.upload()

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

image = cv2.imread(image_filename)

# Ensure image is loaded correctly, otherwise cv2_imshow will error
if image is None:
    print(f"Error: Could not load image from {image_filename}")
else:
    kernel = np.array([[0, 1, 0],
                       [1, -8, 1],
                       [0, 1, 0]])
    sharpened = cv2.filter2D(image, -1, kernel)

    # Convert BGR to RGB for matplotlib display
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    sharpened_rgb = cv2.cvtColor(sharpened, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(image_rgb)
    plt.title('Original Image')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(sharpened_rgb)
    plt.title('Sharpened Image')
    plt.axis('off')

    plt.tight_layout()
    plt.show()