# -*- coding: utf-8 -*-
"""EXP 24

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_ZlOqkCY6kJxEEY97xGY_m0zQrSrrDI
"""

import cv2
import numpy as np
from google.colab import files

def high_boost_filter(image, boost_factor):
    # Ensure image is not None for further processing
    if image is None:
        print("Error: Input image is empty.")
        return None

    kernel_size = 3
    # blur_factor is not used, so removing it
    kernel = np.ones((kernel_size, kernel_size), dtype=np.float32) / (kernel_size ** 2)
    blur_image = cv2.filter2D(image, -1, kernel)
    mask = image + (image - blur_image) * boost_factor
    return mask

# Upload the image file
uploaded = files.upload()

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

image = cv2.imread(image_filename)

# Check if the image was loaded successfully
if image is not None:
    sharpened_image = high_boost_filter(image, 1.5)
    if sharpened_image is not None:
        # Ensure the sharpened image is in a displayable format for saving if it's float
        # Convert to uint8 and clip values to 0-255 range
        sharpened_image_uint8 = np.clip(sharpened_image, 0, 255).astype(np.uint8)
        cv2.imwrite('sharpened_image.jpg', sharpened_image_uint8)
        print(f"Sharpened image saved as sharpened_image.jpg")
else:
    print(f"Error: Could not load image from {image_filename}")

import matplotlib.pyplot as plt

# Load the original image (it was already loaded in the previous cell into 'image')
# However, to ensure we are working with the latest, we will reload it from the filename
original_image_display = cv2.imread(image_filename)
original_image_display = cv2.cvtColor(original_image_display, cv2.COLOR_BGR2RGB)

# Load the sharpened image saved previously
sharpened_image_loaded = cv2.imread('sharpened_image.jpg')
sharpened_image_loaded = cv2.cvtColor(sharpened_image_loaded, cv2.COLOR_BGR2RGB)

# Display images side-by-side
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
plt.imshow(original_image_display)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
plt.imshow(sharpened_image_loaded)
plt.title('Sharpened Image')
plt.axis('off')

plt.tight_layout()
plt.show()