# -*- coding: utf-8 -*-
"""e 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdqkI6OZCX4xRKYBjVnVZdvpLloldwUe
"""

from google.colab import files
files.upload()

import cv2
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread('Screenshot 2025-12-04 121433.png')

# Check if image was loaded successfully
if img is None:
    print("Error: Could not load image. Please check the file name and ensure the image exists.")
else:
    # Clockwise rotation (90 degrees)
    clockwise = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

    # Counter-clockwise rotation (90 degrees)
    counter = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

    # Display images
    print("Original Image:")
    cv2_imshow(img)
    print("Clockwise Rotation:")
    cv2_imshow(clockwise)
    print("Counter Clockwise Rotation:")
    cv2_imshow(counter)