# -*- coding: utf-8 -*-
"""exp 17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCCcNSC8j2N_xYHdGO58TTGZ6aVcNk6Q
"""

import matplotlib.pyplot as plt

# Read the generated Sobel image
sobel_image = cv2.imread('sobel_x.jpg', 0) # Read as grayscale

# Display the image
plt.figure(figsize=(8, 6))
plt.imshow(sobel_image, cmap='gray')
plt.title('Sobel X Edge Detection Result')
plt.axis('off')
plt.show()